name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Job to run tests on pull requests to main
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --watch=false --bail --ci

  # Job to deploy to AWS Elastic Beanstalk on push to main
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Compress Files
        run: zip --symlinks -r my-api.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Init Elastic Beanstalk
        run: echo "n" | eb init my-api --region ${{vars.AWS_REGION}}

      - name: Deploy to Elastic Beanstalk
        run: eb deploy test --staged --label nestjs-${{github.event.repository.pushed_at}}
